# huggingface docker image region us-east-1
From 564829616587.dkr.ecr.us-east-1.amazonaws.com/huggingface-training:pytorch1.6.0-transformers4.3.1-tokenizers0.10.1-datasets1.2.1-py36-gpu-cu110

RUN pip uninstall transformers -y
RUN pip install git+https://github.com/yl-to/transformers.git@profile
